### ISSUE TITLE
404 Page not Found

### ISSUE THREAD

**Issue by Andware** [scoumbourdis/grocery-crud-codeigniter-4#7]
Hello 

I am new on php and Codeigniter 4 with grocery-crud-codeigniter-4 and have not much knowledge om php or codeigniter yet.
I have installed which are described in Readme file but i recipient every time a message that site not found (404 Page not found)!

Jeg har installeret Codeigniter 3 med købmand 1.6.3 og der har jeg ikke nogen problemer.

Can you tell me what I'm doing wrong. Maybe it has something more Routes to do?

Here some more info:

<body>
	<div class="wrap">
		<>404 - File Not Found</>

		<p>
							Controller method is not found: index					</p>
	</div>
</body>
Here some more info:

**Comment by scoumbourdis** [comment]
Hello @Andware ,

I've added 1 line explaining how to access the URL for Codeigniter 4. Please also check the issue here: https://github.com/scoumbourdis/grocery-crud-codeigniter-4/issues/6

Closing issue as this seems that it is not related with the Grocery CRUD but environmental (e.g. Codeigniter 4 project doesn't work as expected)

Regards
Johnny
