### ISSUE TITLE
can i  cange "site_url" to "base_url" in the CI4 for remove index.php???

### ISSUE THREAD

**Issue by FranzaLeny** [scoumbourdis/grocery-crud-codeigniter-4#9]
https://github.com/scoumbourdis/grocery-crud-codeigniter-4/blob/b92c31be2a84328445b4f7001fff7889d289ad3a/app/Libraries/GroceryCrud.php#L3118
Can i cange "site_url" to"base_url" for remove index.php in Codeigniter 4

$state_url =  base_url(implode('/',$state_url_array) . $operation);

**Comment by scoumbourdis** [comment]
This is a configuration in Codeigniter 4. In order to remove `index.php` that is there by default go to: `app/Config/App.php` and change the line at around 36:

    public $indexPage = 'index.php';

to:

     public $indexPage = '';

Closing the ticket as this is not related with Grocery CRUD library but how site_url on Codeigniter works. For more also check the Codeigniter documentation: https://codeigniter.com/user_guide/helpers/url_helper.html

Regards
Johnny
